spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: hare
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: hare

